######################################################################
# Automatically generated by qmake (1.06c) Sun Oct 3 19:37:41 2004
######################################################################

QT += core gui opengl

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app

unix {
    LIBS += -L/usr/local/lib -lGLU
}

# Input
HEADERS += ch9.h \
    nehewidget.h
SOURCES += main.cpp \
    nehewidget.cpp

RESOURCES += \
    res.qrc
